CREATE TABLE IF NOT EXISTS CAR (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    ID_BRAND REFERENCES BRAND(ID)
);

CREATE TABLE IF NOT EXISTS BRAND (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ADDRESS (
    ID SERIAL PRIMARY KEY,
    STREET VARCHAR(255),
    NUMBER VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PERSON (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    ID_ADRESS REFERENCES ADRESS(ID)
);

CREATE TABLE IF NOT EXISTS AUTHOR (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    ID_BOOK REFERENCES BOOK(ID)
);

CREATE TABLE IF NOT EXISTS BOOK (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TASKS (
    ID SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    CATEGORY_ID INT REFERENCES CATEGORIES(ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
);

CREATE TABLE IF NOT EXISTS CAR_MODEL (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    CAR_BRAND_ID INT REFERENCES CAR_BRAND(ID)
);

CREATE TABLE IF NOT EXISTS CAR_BRAND (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
);


