CREATE TABLE IF NOT EXISTS CAR (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    ID_BRAND REFERENCES BRAND(ID)
);

CREATE TABLE IF NOT EXISTS BRAND (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);